'use client'

import { NodeViewWrapper } from '@tiptap/react'
import type { NodeViewProps } from '@tiptap/react'

export function RawHtmlNodeView({ node }: NodeViewProps) {
  return (
    <NodeViewWrapper>
      {/* SVG content is generated by the publish-note.mjs CLI from the author's own HTML files.
          If user-generated SVG content is ever supported, add DOMPurify sanitization here. */}
      <div dangerouslySetInnerHTML={{ __html: (node.attrs.html as string) ?? '' }} />
    </NodeViewWrapper>
  )
}
